# Generated by Django 4.2.7 on 2026-01-11 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for blog listing')),
                ('content', models.TextField(help_text='Full HTML content of the blog')),
                ('meta_description', models.TextField(help_text='SEO meta description (150-160 characters)', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='SEO keywords (optional)', null=True)),
                ('featured_image', models.URLField(help_text='Featured image URL', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('views_count', models.IntegerField(default=0, help_text='Number of views')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
