# Generated by Django 4.2.7 on 2026-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_scheduled_at_alter_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
