# Generated by Django 4.2.7 on 2026-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_scheduled_at_alter_blog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Featured image URL', max_length=1000),
        ),
    ]
