# Generated by Django 4.2.7 on 2026-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandpageLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing Page Lead',
                'verbose_name_plural': 'Landing Page Leads',
                'db_table': 'landpage_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='landpagelead',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_landpage_lead'),
        ),
    ]
