# Generated by Django 5.2.3 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('interested_courses', models.CharField(blank=True, choices=[('digitalmarketing', 'Complete Digital Marketing'), ('seomastery', 'SEO Mastery'), ('socialmediamarketingpro', 'Social Media Marketing Pro'), ('googleads', 'Google Ads & PPC Expert'), ('emailmarketing', 'Email Marketing Specialist'), ('analyticsanddatainsights', 'Analytics & Data Insights'), ('content', 'Content Strategy & Creation')], max_length=50, null=True)),
                ('experience', models.CharField(blank=True, choices=[('fresher', 'Fresher / Student'), ('0-2', '0-2 Years'), ('2-5', '2-5 Years'), ('5+', '5+ Years'), ('switcher', 'Career Switcher')], max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('full_name', 'email', 'phone'), name='unique_contact_entry')],
            },
        ),
    ]
