# Generated by Django 5.2.3 on 2025-07-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='learning_goals',
            new_name='message',
        ),
    ]
