# Generated by Django 4.2.7 on 2026-01-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_interested_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='experience',
            field=models.CharField(blank=True, choices=[('fresher_student', 'Fresher/Student'), ('working_professional', 'Working Professional / Career Switchers'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancers / Remote Jobs Seekers'), ('home_maker', 'Home Makers'), ('others', 'Others')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interested_courses',
            field=models.CharField(blank=True, choices=[('master_dm_internship', 'Master in DM with Internship'), ('specialist_dm', 'Specialist in DM'), ('dm_business_owners', 'DM for Business Owners'), ('foundation_basic_dm', 'Foundation/Basic in DM Course'), ('custom_dm', 'Custom DM Course')], max_length=50, null=True),
        ),
    ]
