# Generated by Django 4.2.16 on 2025-10-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReportLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(choices=[('seomastery', 'SEO Mastery'), ('socialmediapro', 'Social Media Pro'), ('googleadsexpert', 'Google Ads Expert'), ('cmbootcamp', 'Content Marketing Bootcamp'), ('emailmarketingpro', 'Email Marketing Pro'), ('advancedseo', 'Advanced SEO')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('full_name', 'email', 'phone', 'course')},
            },
        ),
    ]
