# Generated by Django 5.2.3 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(blank=True, choices=[('Complete Digital Marketing', 'Complete Digital Marketing'), ('SEO Specialist', 'SEO Specialist'), ('Social Media Marketing', 'Social Media Marketing'), ('Google Ads Mastery', 'Google Ads Mastery'), ('Content Marketing', 'Content Marketing'), ('Email Marketing Pro', 'Email Marketing Pro')], max_length=50, null=True)),
                ('learning_goals', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('full_name', 'email', 'phone', 'course'), name='unique_demo_booking')],
            },
        ),
    ]
