# Generated by Django 5.2.3 on 2025-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demo',
            constraint=models.UniqueConstraint(fields=('full_name', 'email', 'phone', 'course'), name='unique_demo_booking'),
        ),
    ]
