# Generated by Django 4.2.16 on 2025-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='course',
            field=models.CharField(blank=True, choices=[('Complete Digital Marketing', 'Master in Digital Marketing Course at idigitalstudies'), ('SEO Specialist', 'Digital Marketing Specialist Course at iDigitalStudies'), ('Social Media Marketing', 'Best Digital Marketing Course for Business Owners'), ('Google Ads Mastery', 'Digital Marketing Course for Beginners'), ('Content Marketing', 'Customised Course in Digital Marketing'), ('Email Marketing Pro', 'Degree in Digital Marketing')], max_length=50, null=True),
        ),
    ]
