# Generated by Django 4.2.16 on 2025-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_demo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='course',
            field=models.CharField(blank=True, choices=[('Master in Digital Marketing Course at idigitalstudies', 'Master in Digital Marketing Course at idigitalstudies'), ('Digital Marketing Specialist Course at iDigitalStudies', 'Digital Marketing Specialist Course at iDigitalStudies'), ('Best Digital Marketing Course for Business Owners', 'Best Digital Marketing Course for Business Owners'), ('Digital Marketing Course for Beginners', 'Digital Marketing Course for Beginners'), ('Customised Course in Digital Marketing', 'Customised Course in Digital Marketing'), ('Degree in Digital Marketing', 'Degree in Digital Marketing')], max_length=100, null=True),
        ),
    ]
