# Generated by Django 4.2.16 on 2025-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_demo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='course',
            field=models.CharField(blank=True, choices=[('mdm', 'Master in Digital Marketing Course at idigitalstudies'), ('dms', 'Digital Marketing Specialist Course at iDigitalStudies'), ('smb', 'Best Digital Marketing Course for Business Owners'), ('beg', 'Digital Marketing Course for Beginners'), ('cus', 'Customised Course in Digital Marketing'), ('deg', 'Degree in Digital Marketing')], max_length=100, null=True),
        ),
    ]
