# Generated by Django 4.2.7 on 2026-01-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_demo_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('fresher_student', 'Fresher/Student'), ('working_professional', 'Working Professional / Career Switchers'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancers / Remote Jobs Seekers'), ('home_maker', 'Home Makers'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demo',
            name='course',
            field=models.CharField(blank=True, choices=[('master_dm_internship', 'Master in DM with Internship'), ('specialist_dm', 'Specialist in DM'), ('dm_business_owners', 'DM for Business Owners'), ('foundation_basic_dm', 'Foundation/Basic in DM Course'), ('custom_dm', 'Custom DM Course')], max_length=100, null=True),
        ),
    ]
