# Generated by Django 4.2.7 on 2026-01-20 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_demo_experience_level_alter_demo_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='demo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 20, 18, 18, 15, 219203, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
