# Generated by Django 4.2.7 on 2026-01-12 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/role name', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('type', models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], default='hybrid', help_text='Work type', max_length=20)),
                ('duration', models.CharField(help_text='Duration (e.g., 3 months, Full-time)', max_length=100)),
                ('stipend', models.CharField(help_text='Stipend/Salary (e.g., ₹8,000/month)', max_length=100)),
                ('description', models.TextField(help_text='Job description')),
                ('skills', models.JSONField(default=list, help_text='List of required skills')),
                ('requirements', models.JSONField(default=list, help_text='List of job requirements')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('applications_count', models.IntegerField(default=0, help_text='Number of applications')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
