# Generated by Django 4.2.7 on 2026-01-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duration',
            field=models.CharField(help_text='Duration (e.g., 3 months, 6 months)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(help_text='Job location (e.g., Mumbai, Maharashtra)', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(help_text='Job requirements (one per line)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(help_text='Required skills (comma separated)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(help_text='Job title (e.g., Digital Marketing Intern)', max_length=200),
        ),
    ]
