# Generated by Django 4.2.7 on 2026-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_options_remove_vacancy_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='duration',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_description_body',
            field=models.TextField(blank=True, help_text='Full job description in text format', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_description_file',
            field=models.FileField(blank=True, help_text='Job description file (PDF, DOCX, JPG, JPEG)', null=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_description_header',
            field=models.CharField(blank=True, default='', help_text='Job description header (1-liner displayed above skills)', max_length=500),
        ),
    ]
