# Generated by Django 4.2.7 on 2026-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_remove_vacancy_description_remove_vacancy_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, help_text='Company name', max_length=200, null=True),
        ),
    ]
