# Generated by Django 4.2.7 on 2026-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterseoLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, choices=[('student', 'Student'), ('working_professional', 'Working Professional / Career Switchers'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancer'), ('job_seeker', 'Job Seeker')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master SEO Lead',
                'verbose_name_plural': 'Master SEO Leads',
                'db_table': 'master_seo_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='masterseoleads',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_master_seo_lead'),
        ),
    ]
