# Generated by Django 4.2.7 on 2026-01-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('master_dm_internship', 'Master in DM with Internship'), ('specialist_dm', 'Specialist in DM'), ('dm_business_owners', 'DM for Business Owners'), ('foundation_basic_dm', 'Foundation/Basic in DM Course'), ('custom_dm', 'Custom DM Course')], max_length=100)),
                ('course_title', models.CharField(max_length=300)),
                ('experience_level', models.CharField(choices=[('fresher_student', 'Fresher/Student'), ('working_professional', 'Working Professional / Career Switchers'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancers / Remote Jobs Seekers'), ('home_maker', 'Home Makers'), ('others', 'Others')], max_length=100)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Online Demo Booking',
                'verbose_name_plural': 'Online Demo Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='onlinedemo',
            constraint=models.UniqueConstraint(fields=('full_name', 'email', 'phone', 'course'), name='unique_online_demo_booking'),
        ),
    ]
