# Generated by Django 5.2.3 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('experience', models.CharField(blank=True, choices=[('beginner', 'Beginner (New to Digital Marketing)'), ('intermediate', 'Intermediate (Some experience)'), ('advanced', 'Advanced (Experienced professional)')], max_length=20, null=True)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('course_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('full_name', 'email', 'phone', 'course_title')},
            },
        ),
    ]
