# Generated by Django 5.2.3 on 2025-07-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('full_name', 'email', 'phone', 'course_title')},
        ),
    ]
