# Generated by Django 4.2.7 on 2026-01-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='experience',
            field=models.CharField(blank=True, choices=[('fresher_student', 'Fresher/Student'), ('working_professional', 'Working Professional / Career Switchers'), ('business_owner', 'Business Owner'), ('freelancer', 'Freelancers / Remote Jobs Seekers'), ('home_maker', 'Home Makers'), ('others', 'Others')], max_length=30, null=True),
        ),
    ]
