# Generated by Django 5.2.3 on 2025-07-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course_price',
        ),
    ]
