# Generated by Django 5.2.3 on 2025-07-12 16:26

import placement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher (0-6 months))'), ('beginner', 'Beginner (6 months - 1 year))'), ('advanced', 'Intermediate (1-2 years)'), ('experienced', 'experienced (2+ years)')], max_length=20, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[placement.models.validate_file_type, placement.models.validate_file_size])),
            ],
        ),
    ]
