# Generated by Django 5.2.3 on 2025-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='job_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
