# Generated by Django 5.2.3 on 2025-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher (0-6 months))'), ('beginner', 'Beginner (6 months - 1 year))'), ('intermediate', 'Intermediate (1-2 years)'), ('experienced', 'experienced (2+ years)')], max_length=20, null=True),
        ),
    ]
