# Generated by Django 5.2.3 on 2025-07-25 20:03

import placement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placement_job_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_mail', models.EmailField(max_length=254)),
                ('salary_range', models.CharField(max_length=100)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('employee_count', models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20)),
                ('industry_type', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('media', 'Media & Entertainment'), ('other', 'Other')], max_length=50)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('job_profile', models.CharField(max_length=255)),
                ('job_opening_count', models.PositiveIntegerField()),
                ('job_description_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=10)),
                ('job_description_text', models.TextField(blank=True, null=True)),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/', validators=[placement.models.validate_file_type, placement.models.validate_file_size])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
