# Generated by Django 4.2.7 on 2026-01-20 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
