# Generated by Django 4.2.7 on 2026-02-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_placement_options_placement_created_at'),
    ]

    operations = [
        migrations.RenameModel(old_name='Placement', new_name='Register_For_Job'),
        migrations.RenameModel(old_name='Company', new_name='Recruiter'),
]
