# Generated by Django 4.2.7 on 2026-02-03 07:16

from django.db import migrations, models
import placed_students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('certificate_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_image', models.ImageField(upload_to='placed_students/images/', validators=[placed_students.models.validate_image_type, placed_students.models.validate_image_size])),
                ('company_name', models.CharField(max_length=200)),
                ('student_role', models.CharField(max_length=200)),
                ('student_bio', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='placed_students/certificates/', validators=[placed_students.models.validate_certificate_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Placed Student',
                'verbose_name_plural': 'Placed Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
